### ISSUE TITLE
Can not return list of context paths?

### ISSUE THREAD

**Issue by alonsopg** [src-d/code2vec#13]
After installing babel fish, and doing some modifications to the source code (e.g., I changed `Node` for `node` in `bblfsh.node` in `/structures/extended_node.py` file) I did:

```
>>> import bblfsh
>>> from algorithms.path_contexts import get_paths

>>> from pprint import pprint
>>> code = bblfsh.BblfshClient("0.0.0.0:9432").parse(filename='/file.java')
>>> get_paths(code.root, 30, 15)
```
However, I am getting a key error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-20-ffd3713eb283> in <module>
      2 
      3 
----> 4 get_paths(code.root, 30, 15)

~/code2vec_2/src/algorithms/path_contexts.py in get_paths(uast, max_length, max_width, token_extractor, leaf_token)
    135             u, v = leaves[i], leaves[j]
    136             # TODO decide where to filter comments and maybe decouple from bblfsh
--> 137             if not is_noop_line(u) and not is_noop_line(v):
    138                 ancestor = lca(u, v)
    139                 d = distance(u, v, ancestor)

~/code2vec_2/src/algorithms/path_contexts.py in is_noop_line(node)
    109 # dirty hardcoding to avoid getting paths with comments as start/end
    110 def is_noop_line(node):
--> 111     return node.bn.internal_type == 'NoopLine' or node.bn.internal_type == 'SameLineNoops'
    112 
    113 

~/anaconda3/envs/sourced/lib/python3.6/site-packages/bblfsh-3.1.1-py3.6-linux-x86_64.egg/bblfsh/node.py in internal_type(self)
    194     @property
    195     def internal_type(self) -> str:
--> 196         return self.get_dict()["@type"]
    197 
    198     @internal_type.setter

KeyError: '@type'

```
What is the correct way of using `get_paths` function? If my purpose is to get the list of paths context like  `(u, path, v)`?

**Comment by kafkasl** [comment]
The error you are getting is caused because of the change you made to the node. Currently `path_contexts.py` get the type of a node and its token as `node.bn.internal_type` and `node.bn.token`. Changing the node, the function `is_noop_line(...)` does not find the type of the node where it is expected which is your KeyError. 

For the node token, you can provide a custom lambda function to the `get_paths` function that will be used to get the token of the leaf/terminal nodes. Currently, `lambda node: node.bn.token` is used because `blfsh.node` has a an attribute called token. You should change the lambda function to retrieve the token from your custom node.

The same applies to the node type which is retrieved by the function passed to `token_extractor`. 

However in the function `is_noop_line` the  `node.bn.internal_type` is hardcoded (it should use the `token_extractor` defined function) . This is only used to avoid getting paths that start/end with comments (comments have internal type equal to `NoopLine` or `SameLineNoops`).  Either pass the `token_extractor` to work with your custom nodes, or just comment it and return False (this way you'll get paths with comments as start/end but you can filter it afterwards.

The `get_paths` functions just needs to be called from the root of the AST that you'd like to get the paths from and passing the desired depth,

**Comment by alonsopg** [comment]
Thanks for the help and info! However, I still dont get how to use the `get_paths` function. When I do:

`from algorithms.path_contexts import get_paths`

Without editing a single line of code I get:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-869e883beaed> in <module>
----> 1 from algorithms.path_contexts import get_paths
      2 

~/code2vec_2/src/algorithms/path_contexts.py in <module>
----> 1 from algorithms.structures.extended_node import ExtNode
      2 
      3 import bblfsh
      4 
      5 UP = "UP"

~/code2vec_2/src/algorithms/structures/extended_node.py in <module>
      6 
      7 
----> 8 class ExtNode(object):
      9     """
     10     Extended Node used for efficiently extract paths from a tree structure

~/code2vec_2/src/algorithms/structures/extended_node.py in ExtNode()
     17 
     18     def __init__(self, base_node: bblfsh.Node, depth: int, numeration: int=-1, children=(),
---> 19                  log_parents=()):
     20         """
     21 

AttributeError: module 'bblfsh' has no attribute 'Node'
```
Could you provide an example of how to get the paths from the uast?

**Comment by kafkasl** [comment]
which babelfish version are you using? this was designed for babelfish v1 so if you are using v2 the API probably changed and that's why the import is failing

**Comment by alonsopg** [comment]
Thanks for the help!, I am using the latest one. How reliable is to do a downgrade to the previous version? What should I modify in this version in order to be able to use it with V2 and use these functions to extract paths?

**Comment by kafkasl** [comment]
With respect to downgrading, all the code was peer-reviewed and tested by source{d} developers so it does work. 
For the porting, I've been looking at the changes with V2 and it shouldn't be too hard. On one hand `Node` class now lives under  `bblfsh.node.Node` instead of `bblfsh.Node` which is straightforward to change. The other issue is how to iterate over the children of a node. Currently, this is done with `node.children`. However, the new API does not have that attribute and instead uses iterators like `node.iterate(bblfsh.TreeOrder.LEVEL_ORDER)`.
I do not have time to port it myself but if you have any other question feel free to ask. Also, source{d} slack is very active and I've always got help from them when needed so it might be a good option to ask them about porting to V2, you can also find me there as Pol Alvarez if you prefer to discuss this through IM.
